### ISSUE TITLE
torch_xla出现错误undefined symbol: 

### ISSUE THREAD

**Issue by 2018211801** [liuqidong07/MOELoRA-peft#6]
作者你好呀，请问我出现了这个错误该怎么解决呢，我的环境是按照requirements配置的

Traceback (most recent call last):                                                                                                     File "run_mlora.py", line 6, in <module>
    from src.MLoRA.main import main
  File "/cognitive_comp/chen/projects/MOELoRA-peft/src/MLoRA/main.py", line 42, in <module>
    from src.MLoRA.trainer_seq2seq import Seq2SeqTrainer
  File "/cognitive_comp/chen/projects/MOELoRA-peft/src/MLoRA/trainer_seq2seq.py", line 27, in <module>                           from .trainer import Trainer
  File "/cognitive_comp/chen/projects/MOELoRA-peft/src/MLoRA/trainer.py", line 41, in <module>
    from transformers.integrations import (
  File "/home/chen/miniconda3/envs/moet12/lib/python3.8/site-packages/transformers/integrations.py", line 71, in <module>
    from .trainer_callback import ProgressCallback, TrainerCallback  # noqa: E402
  File "/home/chen/miniconda3/envs/moet12/lib/python3.8/site-packages/transformers/trainer_callback.py", line 27, in <module>    from .training_args import TrainingArguments
  File "/home/ochen/miniconda3/envs/moet12/lib/python3.8/site-packages/transformers/training_args.py", line 69, in <module>
    import torch_xla.core.xla_model as xm
  File "/home/hen/miniconda3/envs/moet12/lib/python3.8/site-packages/torch_xla/__init__.py", line 114, in <module>
    import _XLAC
ImportError: /home/chen/miniconda3/envs/moet12/lib/python3.8/site-packages/_XLAC.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZNK5torch4lazy4Node16nullable_operandEm

**Comment by KaiyangWan** [comment]
I have the same issue as you

**Comment by liuqidong07** [comment]
> 作者你好呀，请问我出现了这个错误该怎么解决呢，我的环境是按照requirements配置的
> 
> Traceback (most recent call last): File "run_mlora.py", line 6, in from src.MLoRA.main import main File "/cognitive_comp/chen/projects/MOELoRA-peft/src/MLoRA/main.py", line 42, in from src.MLoRA.trainer_seq2seq import Seq2SeqTrainer File "/cognitive_comp/chen/projects/MOELoRA-peft/src/MLoRA/trainer_seq2seq.py", line 27, in from .trainer import Trainer File "/cognitive_comp/chen/projects/MOELoRA-peft/src/MLoRA/trainer.py", line 41, in from transformers.integrations import ( File "/home/chen/miniconda3/envs/moet12/lib/python3.8/site-packages/transformers/integrations.py", line 71, in from .trainer_callback import ProgressCallback, TrainerCallback # noqa: E402 File "/home/chen/miniconda3/envs/moet12/lib/python3.8/site-packages/transformers/trainer_callback.py", line 27, in from .training_args import TrainingArguments File "/home/ochen/miniconda3/envs/moet12/lib/python3.8/site-packages/transformers/training_args.py", line 69, in import torch_xla.core.xla_model as xm File "/home/hen/miniconda3/envs/moet12/lib/python3.8/site-packages/torch_xla/**init**.py", line 114, in import _XLAC ImportError: /home/chen/miniconda3/envs/moet12/lib/python3.8/site-packages/_XLAC.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZNK5torch4lazy4Node16nullable_operandEm

您好，

请问您使用的硬件平台是什么呢？GPU和CPU的型号

**Comment by 1605wzf** [comment]
我也有同样的问题，GPU是A800

**Comment by liuqidong07** [comment]
@1605wzf @KaiyangWan @2018211801 哈喽，我发现我论文里的python版本写错了，实际使用的是python 3.9.5，论文里写成了3.6.5，抱歉！建议把python版本升至3.9以上。这个报错我确实没有遇到过，感觉是安装transformers package的问题。我检查了一下requirements是没有问题的，我会把更多我的配置信息update到readme里。感谢对我们论文的关注！

**Comment by 1605wzf** [comment]
> I have the same issue as you我和你有同样的问题

您好！请问您相同的问题有解决吗

**Comment by lvyink** [comment]
> 我也有同样的问题，GPU是A800

我也有同样的问题，GPU是4090

**Comment by 2437528020** [comment]
您好，我也出现了同样的问题，GPU是4090，python版本已经是3.9.5了

**Comment by liuqidong07** [comment]
@lvyink @2437528020 您好，环境问题可以在 #7 中进行讨论。另外，我们使用的cuda版本是10.2，而4090可能使用了更高的版本？

**Comment by wurevvc** [comment]
你好，我也出现了问题，GPU是A100，python3.9和3.10都试过了，还是报错这个问题
